# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ESP32_com/zedboard_master_fixed.xdc

# Block Designs: bd/systeme/systeme.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systeme || ORIG_REF_NAME==systeme} -quiet] -quiet

# IP: bd/systeme/ip/systeme_processing_system7_0_0/systeme_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systeme_processing_system7_0_0 || ORIG_REF_NAME==systeme_processing_system7_0_0} -quiet] -quiet

# XDC: bd/systeme/systeme_ooc.xdc
